//---------------------------------------------------------------
// Font generated by muGUI Font and Bitmap Generator (v.0.1.0.1), 
// available from http://www.muGUI.de
//
// Template for HiTech code, see http://edeca.net/wp/?p=874
//
// Project Name:  LucidaConsole
//---------------------------------------------------------------
#ifndef INC_FONT_LUCIDACONSOLE_H_
#define INC_FONT_LUCIDACONSOLE_H_
//---------------------------------------------------------------
// Group Name: LucidaConsole10_Bold
// Designer: Imported System Font
// Date: 12 Nov 2011
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 13 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------

extern const unsigned char LucidaConsole10_Bold[];//---------------------------------------------------------------
// Group Name: LucidaConsole10
// Designer: Imported System Font
// Date: 12 Nov 2011
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 13 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 96
// Start Character: 32 " "
// Stop Character: 127 "."
//---------------------------------------------------------------
extern const unsigned char LucidaConsole10[];//---------------------------------------------------------------
// Group Name: LucidaConsole8
// Designer: Imported System Font
// Date: 12 Nov 2011
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 10 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char LucidaConsole8[];//---------------------------------------------------------------
// Group Name: LucidaConsole7
// Designer: Imported System Font
// Date: 12 Nov 2011
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 9 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char LucidaConsole7[];
#endif
