//---------------------------------------------------------------
// Font generated by muGUI Font and Bitmap Generator (v.0.1.0.1), 
// available from http://www.muGUI.de
//
// Template for HiTech code, see http://edeca.net/wp/?p=874
//
// Project Name:  Arial Black
//---------------------------------------------------------------
#ifndef INC_FONT_ARIALBLACK_H_
#define INC_FONT_ARIALBLACK_H_
//---------------------------------------------------------------
// Group Name: ArialBlack14
// Designer: Imported System Font
// Date: 12 Nov 2011
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 19 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------

extern const unsigned char ArialBlack14[];//---------------------------------------------------------------
// Group Name: ArialBlack12
// Designer: Imported System Font
// Date: 12 Nov 2011
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 16 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char ArialBlack12[]; //---------------------------------------------------------------
// Group Name: ArialBlack10
// Designer: Imported System Font
// Date: 02 Jun 2012
// Description: Imported System Font
// Byte Orientation: horizontalRight
// Font Height: 14 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char ArialBlack10[];//---------------------------------------------------------------
// Group Name: ArialBlack16
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 20 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char ArialBlack16[];
#endif
