//---------------------------------------------------------------
// Font generated by muGUI Font and Bitmap Generator (v.0.1.0.1), 
// available from http://www.muGUI.de
//
// Template for HiTech code, see http://edeca.net/wp/?p=874
//
// Project Name:  Webdings
//---------------------------------------------------------------

//---------------------------------------------------------------
// Group Name: Webdings14
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 21 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 96
// Start Character: 32 " "
// Stop Character: 127 "."
//---------------------------------------------------------------
#ifndef INC_FONT_WEBDINGS_H_
#define INC_FONT_WEBDINGS_H_
extern const unsigned char Webdings14[];//---------------------------------------------------------------
// Group Name: Webdings16
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 23 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 96
// Start Character: 32 " "
// Stop Character: 127 "."
//---------------------------------------------------------------
extern const unsigned char Webdings16[];//---------------------------------------------------------------
// Group Name: Webdings18
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 25 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 96
// Start Character: 32 " "
// Stop Character: 127 "."
//---------------------------------------------------------------
extern const unsigned char Webdings18[];
#endif
