//---------------------------------------------------------------
// Font generated by muGUI Font and Bitmap Generator (v.0.1.0.1), 
// available from http://www.muGUI.de
//
// Template for HiTech code, see http://edeca.net/wp/?p=874
//
// Project Name:  Wingdings
//---------------------------------------------------------------
#ifndef INC_FONT_WINGDINGS_H_
#define INC_FONT_WINGDINGS_H_
//---------------------------------------------------------------
// Group Name: Wingdings
// Designer: Imported System Font
// Date: 12 Nov 2011
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 21 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------

extern const unsigned char Wingdings[];
#endif
