//---------------------------------------------------------------
// Font generated by muGUI Font and Bitmap Generator (v.0.1.0.1), 
// available from http://www.muGUI.de
//
// Template for HiTech code, see http://edeca.net/wp/?p=874
//
// Project Name:  Verdana
//---------------------------------------------------------------
#ifndef INC_FONT_VERDANA_H_
#define INC_FONT_VERDANA_H_
//---------------------------------------------------------------
// Group Name: Verdana8
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 11 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------

extern const unsigned char Verdana8[];//---------------------------------------------------------------
// Group Name: Verdana10
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 13 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char Verdana10[];//---------------------------------------------------------------
// Group Name: Verdana12
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 16 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char Verdana12[];//---------------------------------------------------------------
// Group Name: Verdana14
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 19 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char Verdana14[];//---------------------------------------------------------------
// Group Name: Verdana16
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 21 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char Verdana16[];//---------------------------------------------------------------
// Group Name: Verdana22
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 29 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char Verdana22[];//---------------------------------------------------------------
// Group Name: Verdana26
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 35 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char Verdana26[] ;//---------------------------------------------------------------
// Group Name: Verdana32
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 44 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern const unsigned char Verdana32[] ;
#endif
